### ISSUE TITLE
Implement user control Assignment2.ascx

### ISSUE THREAD

**Issue by Daniel-Miller** [InSite/Prototype#1]
Here we need to create a large sample data set (100+ rows) that we can use to load an array of CompanyEmployee objects.

The spreadsheet (002.xlsx) shows an example of how the page can render the table. Here we should allow the user to select the column that they want to group by: "Company" or "Company and Department" or "Role"

The search filter should query on the property values Name, Company, Department, and Role

Similar to the the Filter functionality on GitHub Issues, the search input should support the syntax label:value – If no label is input by the user then we assume label = keyword and value = search string enclosed in quotations. For example, the input hello world is assumed to be equivalent to keyword:"hello world".

Implement support for an optional filter employment:value, where value is one of the EmploymentType enumeration values. This will allow the user to filter the table based on CompanyEmployee.Employments.Where( x => x.EmploymentType == input ).

**Comment by Daniel-Miller** [comment]
When you push code for future changes, could you include the Issue # in the commit message? Then we should be able to see links to those commits in the discussion thread here.

**Comment by vvfedosov** [comment]
> 
> 
> When you push code for future changes, could you include the Issue # in the commit message? Then we should be able to see links to those commits in the discussion thread here.

Sorry, don't understand, please give me example, what message I should use for Assignment#2?

**Comment by Daniel-Miller** [comment]
As a next step let's implement some minor cosmetic improvements to the admin/assignment2 page here.

1. Remove the Programming Notes

2. Use a Bootstrap input group for the filter input and search button, so they are rendered together rather than on separate lines, with the Search button on the right.  For example - https://getbootstrap.com/docs/3.3/components/#input-groups-buttons

3. Incorporate the Group By selector into the input-group as a button dropdown on the left. For example - https://getbootstrap.com/docs/3.3/components/#input-groups-buttons-dropdowns

**Comment by Daniel-Miller** [comment]
This looks great - nice work.
